---
format: html
editor: source
editor_options: 
  chunk_output_type: console
execute:
  echo: false
  warning: false
  message: false
  results: "hide"
---

```{r, warning = F, message = F}
# R version 4.3.2 (2023-10-31 ucrt) -- "Eye Holes"
# RStudio 2024.12.0+467 "Kousa Dogwood"

# Packages
library(data.table) # Version ‘1.15.4’
library(tidyverse)  # Version ‘2.0.0’
library(ggrepel)    # Version '4.3.3'
library(ggtext)     # Version ‘0.1.2’
library(readxl)     # Version ‘1.4.3’
library(haven)      # Version ‘2.5.4’

# Colors
mypal <- c("#490B1D", "#888888")
greys <- c("#eaeaea", "#d1d1d1", "#444444")
grad <- c("#000000", "#490B1D", "#ffffff")

# Plot parameters
text_size <- 12
m <- text_size / 2
bwidth <- 6
bheight <- bwidth*(9/16)*1.1
knitr::opts_chunk$set(fig.width = bwidth, fig.height = bheight, fig.align = "center")

# General graph theme
custom_theme <- function() {
  theme(text = element_text(color = greys[3], size = text_size, lineheight = .9),
        # Axes 
        axis.ticks = element_line(color = greys[2]),
        axis.ticks.length = unit(m/2, "pt"),
        axis.line = element_line(color = greys[2]),
        axis.text = element_markdown(),
        axis.title.x = element_markdown(margin = margin(t = m)),
        axis.title.x.top = element_markdown(margin = margin(b = m)),
        axis.title.y = element_markdown(margin = margin(r = m)),
        axis.title.y.right = element_markdown(margin = margin(l = m)),
        # Plot
        plot.margin = margin(m, m, m, m),
        plot.background = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(
          color = greys[1], linetype = "dashed", linewidth = rel(.5)),
        # Legend
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.margin = margin(0, 0, 0, 0, "cm"),
        legend.position = "top", 
        legend.direction = "horizontal", 
        legend.title = element_blank(),
        # Strips
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(
          color = greys[3], margin = margin(m, m, m, m), size = rel(1)))
}

iso_country <- fread("../articles/boustan_et_al_2025/src/iso_country.csv") %>% 
  .[, .(country = name, CTY = `alpha-3`)] %>% 
  .[country == "Netherlands, Kingdom of the", country := "Netherlands"] %>% 
  .[country == "United Kingdom of Great Britain and Northern Ireland", country := "UK"] %>% 
  .[country == "United States of America", country := "USA"] 

linked_men <- read_dta("../articles/boustan_et_al_2025/src/crosssectional_mobility_gap_linked_dataset_men.dta") %>% 
  arrange(country, gen) %>% 
  left_join(iso_country, by = "country")

linked_women <- read_dta("../articles/boustan_et_al_2025/src/crosssectional_mobility_gap_linked_dataset_women.dta") %>% 
  arrange(country, gen) %>% 
  left_join(iso_country, by = "country")

igm_dt <- read_dta("../articles/boustan_et_al_2025/src/igm_regression.dta")
```


# Convergence between generations

## Linked data

```{r}
# Prepare data
convergence_dt <- rbind(linked_women %>% mutate(gender = "Women"),
                        linked_men %>% mutate(gender = "Men") ) %>% 
  group_by(country) %>%
  mutate(coef1 = max(ifelse(gen == 1 & gender == "Men", coef, NA), na.rm = T),
         gen = ifelse(gen == 2, "Children", "Parents"),
         order_gen = as.numeric(gen == "Children")) %>% 
  ungroup() %>%
  arrange(coef1) %>% 
  mutate(order_country = ceiling(row_number()/2),
         gender_country = paste(country, gender))

# Plot
ggplot(convergence_dt, aes(x = coef, 
                           y = reorder(country, order_country), 
                           color = gender,
                           group = gender_country)) +
  
  # Draw arrows with a (2/3)-point gap between arrow ends and actual points
  geom_path(data = convergence_dt %>% 
              select(coef, country, year, gen, gender, order_country, gender_country) %>% 
              pivot_wider(names_from = gen, values_from = coef) %>% 
              mutate(Parents = ifelse(Parents - Children > 0, Parents - (2/3), Parents + (2/3)),
                     Children = ifelse(Parents - Children < 0, Children - (2/3), Children + (2/3))) %>% 
              pivot_longer(c("Parents", "Children"), names_to = "gen", values_to = "coef"),
            arrow = arrow(length = unit(0.02, "npc")), alpha = .6, 
            position = position_dodge(width = .5), linewidth = .5)  +
  
  # Actual points 
  geom_point(aes(shape = reorder(factor(gen), order_gen)), alpha = .6, 
             position = position_dodge(c(.5, .5000000000001))) + 
             # bugs with c(.5, .5) // must figure out what's up with the warning 
  
  # Annotations
  annotate("text", x = 0, y = .5, label = "Equality", 
           alpha = .8, color = greys[3], size = 4, hjust = 0) +
  annotate("segment", x = 0, y = 2.5, xend = 0, yend = 15.5, linetype = "longdash", 
           alpha = .6, color = greys[3]) +
  
  # Overall layout
  scale_x_continuous(paste("Income rank point gap"), limits = c(-22, 10)) +
  
  scale_shape_manual("Generation:", values = c(16, 17), 
                     guide = guide_legend(override.aes = list(color = greys[3]))) +
  scale_color_manual(values = c("#799bb3", "#490B1D")) +
  coord_flip() + custom_theme() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_markdown(angle = 45, hjust = 1),
        panel.grid.major.x = element_blank())

# Save plot
ggsave("../articles/boustan_et_al_2025/out/gaps.png", width = bwidth, height = bheight)
```


# Country scatter plots (3-letter codes)

```{r}
country_scatter <- function(i, labvar = "CTY") {
  
  # Reshape data and compute gap between point and label based on CI
  test_dt <- get(i) %>%
    pivot_longer(c(coef, ci_lower, ci_upper), names_to = "coef", values_to = "value") %>%
    mutate(label = paste0(coef, gen))%>% 
    select(label, country, CTY, value) %>% 
    pivot_wider(names_from = "label", values_from = "value")  %>%
    mutate(ywidth = abs(ci_lower2 - ci_upper2),
           xwidth = abs(ci_lower1 - ci_upper1))
  
  # Fit parameters
  mdl <- lm(formula = coef2 ~ coef1, data = test_dt)
  
  coefs <- mdl$coefficients
  slp <- round(summary(mdl)$coefficients[2, 1], 2)
  se <- round(summary(mdl)$coefficients[2, 2], 2)
  
  # Plot
  p <- ggplot(test_dt, aes(x = coef1, y = coef2)) +
    
    # Annotate divergence
    geom_ribbon(data = data.table(coef1 = c(-25, 0, 0, 15),
                                  coef2 = c(-25, 0, 0, 15), 
                                  country = NA,
                                  ymin = c(-25, -25, 0, 15), 
                                  ymax = c(-25, 0, 15, 15)), 
                aes(ymin = ymin, ymax = ymax), fill = mypal[1], alpha = .125) +
    annotate("text", x = -12.5, y = -25, label = "Divergence", 
             alpha = .6, color = mypal[1], size = 3.5, vjust = -0.4) +
    
    # Annotate convergence
    geom_ribbon(data = data.table(coef1 = c(-25, 0, 0, 15),
                                  coef2 = c(-25, 0, 0, 15), 
                                  country = NA,
                                  ymin = c(-25, 0, 0, 0), 
                                  ymax = c(0, 0, 0, 15)), 
                aes(ymin = ymin, ymax = ymax), fill = mypal[2], alpha = .075) +
    annotate("text", x = -25, y = -12.5, label = "Convergence", angle = 90, 
             alpha = .8, color = mypal[2], size = 3.5, vjust = 1.3) +
    
    # Annotate slope
    annotate("text", x = -15, y = 13.5, size = 3.5, 
             label = paste0("Slope = ", slp, " (s.e. = ", sprintf("%.2f", se), ")"), 
             alpha = .8, color = greys[3]) +
    
    # Annotate persistence
    annotate("text", x = -22, y = -22, label = "Persistance", size = 3.5, 
             angle = 30.5, alpha = .6, color = greys[3]) +
    annotate("segment", x = -19.5, y = -19.5, xend = 15, yend = 15, 
                 linetype = "solid", alpha = .4, color = greys[3]) +
    
    # Annotate over-taking and fall behind
    annotate("text", x = -25, y = 7.5, label = "Overtaking", angle = 90, 
             alpha = .8, color = mypal[2], size = 3.5, vjust = 1.3) +
    annotate("text", x = 7.5, y = -25, label = "Fall behind",  
             alpha = .6, color = mypal[1], size = 3.5, vjust = -.4) +
    
    # Confidence intervals
    geom_errorbarh(aes(xmin = ci_lower1, xmax = ci_upper1), height = .5, color = alpha(greys[3], .8))+
    geom_errorbar(aes(ymin = ci_lower2, ymax = ci_upper2), width = .5, color = alpha(greys[3], .8))+
    
    # Place countries
    geom_point(size = 1, color = alpha(greys[3], .8)) + 
    geom_text_repel(aes(label = get(labvar)), fontface = "italic", color = alpha(greys[3], .8),
                    max.overlaps=Inf, segment.color = "transparent") +
    
    # Regression line
    annotate("segment", x = -22.5, xend = 12.5,  
             y = coefs[1]-25*coefs[2], yend = coefs[1]+15*coefs[2], 
             linetype = "solid", alpha = .6, color = mypal[1]) +
    
    # Axes
    scale_x_continuous("First-generation income rank point gap", 
                       limits = c(-25, 15), seq(-25, 15, 5), expand = c(0, 0)) +
    scale_y_continuous("Second-generation income rank point gap", 
                       limits = c(-25, 15), seq(-25, 15, 5), expand = c(0, 0)) +
    custom_theme() 
  
return(p)
  
}
```

::: {.panel-tabset}

## Women

```{r}
country_scatter("linked_women", labvar = "country")
ggsave("../articles/boustan_et_al_2025/out/daughters.png", width = bwidth, height = bheight)
```

## Men

```{r}
country_scatter("linked_men", labvar = "country")
ggsave("../articles/boustan_et_al_2025/out/preview.png", width = bwidth, height = bheight)
```




