---
format: html
editor: source
editor_options: 
  chunk_output_type: console
execute:
  echo: false
  warning: false
  message: false
  results: "hide"
---

```{r, warning = F, message = F}
library(ggtext)
library(patchwork)
library(tidyverse)
library(data.table)
library(viridis)
library(readxl)
library(glue)
library(sf)
library(ggmapinset)
library(ggautomap)

mypal <- c("#BB394C", "#888888", "#242424")
greys <- c("#eaeaea", "#d1d1d1", "#444444")
grad <- c("#000000", "#921539", "#dd0747", "#ffffff")
alt_pal <- c("#FCDBB0", "#DD908A", "#BB394C", "#702F38", "#242424")

text_size <- 11
m <- text_size / 2
bwidth <- 6
bheight <- bwidth*(9/16)*1.1

custom_theme <- function() {
  theme(text = element_text(color = greys[3], size = text_size, lineheight = .9),
        axis.ticks = element_line(color = greys[2]),
        axis.ticks.length = unit(m/2, "pt"),
        axis.line = element_line(color = greys[2]),
        axis.text = element_markdown(),
        axis.title.x = element_markdown(margin = margin(t = m)),
        axis.title.x.top = element_markdown(margin = margin(b = m)),
        axis.title.y = element_markdown(margin = margin(r = m)),
        axis.title.y.right = element_markdown(margin = margin(l = m)),
        plot.margin = margin(m, m, m, m),
        plot.background = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = greys[1], linetype = "dashed", linewidth = rel(.5)),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.margin = margin(0, 0, 0, 0, "cm"),
        legend.position = "top", 
        legend.direction = "horizontal", 
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(color = greys[3], size = rel(0.8), margin = margin(m, m, m, m)))
}

alpha_color = .8
```

```{r}
cef <- rbind(
  fread("../articles/kenedi_sirugue_2023/src/fig3B_cef_rank_boot.csv") %>% 
    mutate(country = "France") %>% 
    select(country, p = family_rank, c = child_rank),
  fread("../articles/kenedi_sirugue_2023/src/Aus_rankrank.csv") %>% 
    mutate(country = "Australia") %>% 
    select(country, p = p_rank, c = mean_c_rank),
  read_excel("../articles/kenedi_sirugue_2023/src/Statistics_By_Parent_or_child_Income_Percentile.xlsx", 
             sheet = "By Parent Income Percentile") %>%  
    mutate(country = "United States",
           c = kid_fam_rank * 100) %>%
    select(country, p = par_bin, c = c),
  data.frame(country = "Full mobility", p = 1:100, c = 50.5),
  data.frame(country = "No mobility", p = 25:75, c = 25:75)
) %>% 
  mutate(order_color = case_when(country == "No mobility" ~ 0,
                                 country == "United States" ~ 1,
                                 country == "France" ~ 2,
                                 country == "Australia" ~ 3,
                                 country == "Full mobility" ~ 4))

theory_dt <- data.frame(p = c(101, 101, 101, 101, 78), c = c(50.5, 62, 71.5, 68.5, 75), 
                              country = c("Full mobility", "Australia", "France", "United States", "No mobility"),
                              order_color = 0:4)

p <- ggplot(cef %>% filter(country %chin% c("France", "United States", "Australia")), 
       aes(x = p, y = c, color = reorder(country, order_color))) + 
  geom_point(alpha = .8, show.legend = F) + 
  scale_color_manual(values = c(alt_pal[5], mypal[c(1, 2)])) +
  geom_text(data = theory_dt %>% filter(country %chin% c("France", "United States", "Australia")), 
            aes(label = reorder(country, order_color)), 
            hjust = 0, show.legend = F, alpha = .8) +
  scale_x_continuous("Parents' income percentile rank", limits = c(0, 122), 
                     breaks = c(1, seq(20, 100, 20)), expand = c(0, 0)) +
  scale_y_continuous("Average child income percentile rank", limits = c(25, 75)) +
  custom_theme()

ggsave("../articles/kenedi_sirugue_2023/out/preview.png", p, width = bwidth, height = bheight, dpi = 400)
```

```{r}
dep_shp <- read_sf("../articles/kenedi_sirugue_2023/src/DEPARTEMENT.shp")

dep_shp <- dep_shp %>%
  mutate(dep = ifelse(CODE_DEPT %in% c("2A", "2B"), 20, as.numeric(CODE_DEPT))) %>%
  group_by(dep) %>%
  summarise(geometry = st_union(geometry))

dep_shp <- dep_shp %>% 
  left_join(read.csv("../articles/kenedi_sirugue_2023/src/fig8B_rrc_map.csv"), by = "dep") 

dep_shp <- dep_shp %>%
  separate(rrc, c("lb", "ub"), "-") %>% 
  mutate(rrc = ifelse(is.na(n), 
                      "Insufficient\ndata",
                      paste(round(as.numeric(lb), 2), "-", 
                             round(as.numeric(ub), 2))))

center_idf <- st_geometry(st_point(c(657000, 6862032)))
st_crs(center_idf) <- 2154

p <- ggplot(dep_shp, aes(fill = rrc)) + 
  scale_fill_manual(values = c("#EEBCA9", "#DD908A", "#CC656B", "#BB394C", 
                               "#963442", "#702F38", "#4A2A2E", "#242424", "grey80")) +
 
  geom_sf_inset(color = "transparent", alpha = .83) + coord_automap(inset = configure_inset(
    centre = center_idf, radius = 22, units = "km", scale = 3, translation = c(350, 200))) +
  annotate("segment", x = 657000, xend = 935000, y = 6862032, yend = 7060000, color = mypal[3]) +
   guides(fill = guide_legend(override.aes = list(color = "transparent", alpha = .5))) +
  geom_richtext(data = data.frame(x = 1310000, y = 7000000,
                                  label = "<b>Rank-rank slope:</b>"),
                aes(x = x, y = y, label = label),
                hjust = 0, size = 3, fill = NA, label.color = NA) +
  geom_richtext(data = data.frame(x = 880000, y = 7160000,
                                  label = "<i>Paris region</i>"),
                aes(x = x, y = y, label = label),
                hjust = 0, size = 3, fill = NA, label.color = NA) +
  scale_x_continuous(limits = c(st_bbox(dep_shp)[1], st_bbox(dep_shp)[3] + 400000)) +
  theme_void() +
  theme(text = element_text(size = text_size), 
        legend.position = c(0.855,.5), 
        legend.title = element_blank())

ggsave("../articles/kenedi_sirugue_2023/out/map.png", p, width = bwidth, height = bheight, dpi = 400)
```

```{r}
fig8 <- fread("../articles/kenedi_sirugue_2023/src/fig10_mobility_nat_rank.csv")

pct_movers <- read.csv("../articles/kenedi_sirugue_2023/src/in_text_figures.csv") %>%
  filter(Label == "%movers all") %>% pull(Figure)

p <- fig8 %>%
  mutate(mobility = ifelse(mobility == 1, "Movers", "Stayers")) %>% 
  ggplot(aes(x = family_income_n_spatial_household_income_rank, y = child_rank, color = factor(mobility))) + 
  geom_point(alpha = alpha_color) +
  geom_smooth(method = "lm", se = F, formula = y ~ poly(x, 3, raw = T)) +
  scale_x_continuous(breaks = c(1, seq(20,100,20)), expand = c(0.01, .01)) +
  scale_y_continuous(limits = c(30, 80),  breaks = seq(20,80,10), expand = c(0,0)) +
  scale_color_manual("Geographic:", values = alpha(mypal, alpha_color)) +
  labs(x = "Parent household income rank",
       y = "Child household income rank") +
  custom_theme()

ggsave("../articles/kenedi_sirugue_2023/out/geomob.png", p, width = bwidth, height = bheight, dpi = 400)
```
