---
format: html
editor: source
editor_options: 
  chunk_output_type: console
execute:
  echo: false
  warning: false
  message: false
  results: "hide"
---

```{r, warning = F, message = F}
library(ggtext)
library(patchwork)
library(tidyverse)
library(data.table)
library(viridis)
library(readxl)
library(glue)
library(sf)
library(ggmapinset)
library(ggautomap)

mypal <- c("#BB394C", "#888888", "#242424")
greys <- c("#eaeaea", "#d1d1d1", "#444444")
grad <- c("#000000", "#921539", "#dd0747", "#ffffff")
alt_pal <- c("#FCDBB0", "#DD908A", "#BB394C", "#702F38", "#242424")

text_size <- 11
m <- text_size / 2
bwidth <- 6
bheight <- bwidth*(9/16)*1.1

custom_theme <- function() {
  theme(text = element_text(color = greys[3], size = text_size, lineheight = .9),
        axis.ticks = element_line(color = greys[2]),
        axis.ticks.length = unit(m/2, "pt"),
        axis.line = element_line(color = greys[2]),
        axis.text = element_markdown(),
        axis.title.x = element_markdown(margin = margin(t = m)),
        axis.title.x.top = element_markdown(margin = margin(b = m)),
        axis.title.y = element_markdown(margin = margin(r = m)),
        axis.title.y.right = element_markdown(margin = margin(l = m)),
        plot.margin = margin(m, m, m, m),
        plot.background = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = greys[1], linetype = "dashed", linewidth = rel(.5)),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.margin = margin(0, 0, 0, 0, "cm"),
        legend.position = "top", 
        legend.direction = "horizontal", 
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(color = greys[3], size = rel(0.8), margin = margin(m, m, m, m)))
}
```

```{r}
alpha_fill = .5
parent_distributions <- fread("../articles/sirugue_2024/src/parent_distributions.csv") %>% 
  .[order_mixity == 0 & origin != "Other"] %>% 
  mutate(order_origin = case_when(origin == "France" ~ 0,
                                  origin == "South Europe" ~ 1,
                                  origin == "North Africa" ~ 2)) %>% 
  mutate(gen = "Parents' generation", order_gen = 0)

children_distributions <- fread("../articles/sirugue_2024/src/children_distributions.csv") %>% 
  .[order_mixity == 0 & origin != "Other"] %>% 
  mutate(order_origin = case_when(origin == "France" ~ 0,
                                  origin == "South Europe" ~ 1,
                                  origin == "North Africa" ~ 2)) %>% 
  mutate(gen = "Children's generation", order_gen = 1)

p <- ggplot(rbind(parent_distributions, children_distributions), 
       aes(x = decile, y = pct)) +
  geom_bar(stat = "identity", position = "identity", alpha = .7, fill = mypal[1]) + 
  geom_hline(yintercept = .10, linetype = "dashed", color = greys[3], alpha = .8) +
  facet_grid(reorder(gen, order_gen)~reorder(origin, order_origin), switch = "y") +
  scale_x_continuous("Decile of the overall parents' income distribution", breaks = 1:10) +
  scale_y_continuous("Share of individuals in each decile<br>within generation and origin group", 
                     limits = c(0, .51), breaks = (0:5)/10, labels = paste0((0:5)*10, "%")) +
  custom_theme() 

ggsave("../articles/sirugue_2024/out/preview.png", p, width = bwidth, height = bheight, dpi = 400)
```

```{r}
cefs <- fread("../articles/sirugue_2024/src/cefs_income.csv") %>% 
  filter(origin != "Other") %>% 
  mutate(order_origin = as.numeric(origin == "North Africa"))
  
cefs_income <- lapply(unique(cefs[origin != "France"]$origin), function(x) {
  rbind(cefs[origin == "France", .(child_france = child, Share_france = Share, n_france = n, origin = x, 
                                   gender, decile, mixity = "One native parent")],
        cefs[origin == "France", .(child_france = child, Share_france = Share, n_france = n, origin = x, 
                                   gender, decile, mixity = "No native parent")])
}) %>% rbindlist() %>% 
  full_join(cefs, by = c("gender", "origin", "decile", "mixity")) %>%
  filter(origin != "France") %>%
  group_by(origin) %>% 
  mutate(order_origin = mean(order_origin, na.rm = T)) %>% 
  ungroup() %>% 
  group_by(gender) %>% 
  mutate(order_gender = mean(order_gender, na.rm = T)) %>% 
  ungroup()

p <- cefs_income %>% 
  filter(mixity == "No native parent") %>% 
  pivot_longer(c("child_france", "child", "Share", "Share_france"), names_to = "var", values_to = "val") %>%
  separate(var, c("var", "native"), "_") %>% 
  pivot_wider(names_from = "var", values_from = "val") %>% 
  mutate(parent = ifelse(is.na(native), "Parents born abroad", "Parents born in France"),
         Share = case_when(Share < .05 ~ "< 5%",
                           Share >= .05 & Share <= .15~ "5-15%",
                           Share > .15 ~ "> 15% from decile"),
         order_share = case_when(Share == "< 5%" ~ 1,
                                 Share== "5-15%" ~ 2,
                                 Share == "> 15%" ~ 3)) %>% 
  filter(!is.na(Share)) %>% 
  ggplot(aes(x = decile, y = child, color = parent)) +
  geom_point(aes(size = reorder(Share, order_share)), alpha = .2, shape = 16, show.legend = F) +
  geom_line(stat = "smooth", alpha = .8, se = F, method = "lm") +

  scale_color_manual(values = mypal) + 
  scale_fill_manual(values = mypal) + 

  scale_size_manual(values = c(1, 2, 3)) +
  facet_grid(reorder(gender, order_gender)~reorder(origin, order_origin), switch = "y") +
  scale_x_continuous("Parents\\' income decile", breaks = 1:10) +
  scale_y_continuous("Child average income rank") +
  geom_hline(yintercept = 50.5, linetype = "dotted", color = greys[3], alpha = .8) +
  custom_theme() 

ggsave("../articles/sirugue_2024/out/conditional_gaps.png", p, width = bwidth, height = bheight, dpi = 400)
```

```{r}
comshp <- read_sf("../articles/sirugue_2024/src/COMMUNE.shp") %>% 
  mutate(depcom = paste0(CODE_DEPT, CODE_COMM))

z90 <- fread("../articles/sirugue_2024/src/zonage_1990.csv", colClasses = "character") %>%
  .[, depcom := paste0(D, C)] %>% 
  .[depcom %chin% as.character(69381:69389), depcom := "69123"] %>% 
  .[depcom %chin% as.character(13201:13216), depcom := "13055"]

zshp <- comshp %>%
  left_join(z90 %>% 
              group_by(depcom, UU90) %>%
              summarise(IL = n()) %>% 
              mutate(IL = ifelse(IL > 1, IL, NA)) %>% 
              distinct(), by = "depcom") %>%
  mutate(dep = substr(depcom, 1, 2))

france <- st_union(zshp)
uu_shp <- zshp %>% filter(UU90 != "") %>% group_by(UU90) %>% summarise(geometry = st_union(geometry))

coms90 <-  unique(z90$depcom)
coms97 <-  st_drop_geometry(comshp)$depcom
coms_in_shp97_not_in_rp90 <- coms97[!coms97%chin%coms90]
coms_in_rp90_not_in_shp97 <- coms90[!coms90%chin%coms97]


z90_supp <- lapply(coms_in_shp97_not_in_rp90, function(x){
  
  uu_id <- uu_shp %>% 
    mutate(keep = st_intersects(filter(comshp, depcom == x), uu_shp, sparse = F)[1, ]) %>% 
    filter(keep & !is.na(UU90)) %>%
    st_drop_geometry() %>% 
    pull(UU90) 
  uu_id <- ifelse(length(uu_id) > 0, uu_id, "")
  
  return(data.table(depcom = x, UU90 = uu_id))
}) %>% rbindlist() %>%
  mutate(D = substr(depcom, 1, 2), 
         C = substr(depcom, 3, 5), 
         IL = "0001")

z90 <- rbind(z90[, .(depcom, UU90, D, C, IL)], z90_supp)
```

```{r}
alpha_color <- .8
alpha_fill <- .3

iris35 <- read_sf("../articles/sirugue_2024/src/IRIS35.shp")
iris35 <- st_transform(iris35, st_crs(comshp))

uu35701_shp <- iris35 %>%
  mutate(area = as.numeric(st_area(geometry))) %>% 
  left_join(iris35 %>%  
              st_intersection(comshp %>% 
                                filter(depcom %chin% unique(z90[UU90 == "35701"]$depcom))) %>% 
              mutate(new_area = as.numeric(st_area(geometry))) %>% 
              st_drop_geometry() %>% 
              select(DComIris, new_area)) %>% 
  mutate(share_area = new_area/area) %>% 
  filter(share_area > .5)

iris31 <- read_sf("../articles/sirugue_2024/src/IRIS31.shp")
iris31 <- st_transform(iris31, st_crs(comshp))

uu31701_shp <- iris31 %>%
  mutate(area = as.numeric(st_area(geometry))) %>% 
  left_join(iris31 %>%  
              st_intersection(comshp %>% 
                                filter(depcom %chin% unique(z90[UU90 == "31701"]$depcom))) %>% 
              mutate(new_area = as.numeric(st_area(geometry))) %>% 
              st_drop_geometry() %>% 
              select(DComIris, new_area)) %>% 
  mutate(share_area = new_area/area) %>% 
  filter(share_area > .5)

iris87 <- read_sf("../articles/sirugue_2024/src/IRIS87.shp")
iris87 <- st_transform(iris87, st_crs(comshp))

uu87601_shp <- iris87 %>%
  mutate(area = as.numeric(st_area(geometry))) %>% 
  left_join(iris87 %>%  
              st_intersection(comshp %>% 
                                filter(depcom %chin% unique(z90[UU90 == "87601"]$depcom))) %>% 
              mutate(new_area = as.numeric(st_area(geometry))) %>% 
              st_drop_geometry() %>% 
              select(DComIris, new_area)) %>% 
  mutate(share_area = new_area/area) %>% 
  filter(share_area > .5)
```


```{r}
hydro <- read_sf("../articles/sirugue_2024/src/TRONCON_HYDROGRAPHIQUE.shp") %>%
  select(type = LARGEUR, geometry) %>% 
  filter(type != "De 0 à 15 mètres") %>% 
  mutate(feature = "Waterway") %>% 
  st_cast("LINESTRING")

rails <- read_sf("../articles/sirugue_2024/src/TRONCON_VOIE_FERREE.shp") %>% 
  filter(CLASSEMENT == "En service") %>%
  select(type = NATURE, geometry) %>% 
  mutate(feature = "Railway") %>% 
  st_cast("LINESTRING")

roads <- read_sf("../articles/sirugue_2024/src/TRONCON_ROUTE.shp") %>% 
  filter(CLASS_ADM %in% c("Autoroute", "Nationale")) %>%
  select(type = CLASS_ADM, geometry) %>% 
  mutate(feature = "Roadway") %>% 
  st_cast("LINESTRING")

iv_shp <- rbind(hydro, rails, roads)
iv_shp <- st_transform(iv_shp, st_crs(comshp)) %>% 
  mutate(order_feature = case_when(feature == "Waterway" ~ 1,
                                   feature == "Roadway" ~ 2,
                                   feature == "Railway" ~ 3))

toulouse_iv <- ggplot(st_intersection(st_buffer(uu31701_shp, 100), iv_shp),
       aes(color = reorder(feature, order_feature), fill = reorder(feature, order_feature))) +
  geom_sf(data = st_intersection(france, uu31701_shp), 
          fill = alpha(greys[1], alpha_fill), 
          color = alpha(greys[2], alpha_fill), 
          show.legend = F) + 
  geom_sf(data = st_union(st_intersection(france, uu31701_shp)), 
          fill = NA, 
          color = alpha(greys[2], 1), 
          show.legend = F) + 
  geom_sf(alpha = alpha_color) +
  scale_color_manual(values = c("steelblue", mypal[1:2])) + 
  scale_fill_manual(values = c("steelblue", mypal[1:2])) + 
  custom_theme() +
  ggtitle("Toulouse") +
  theme(panel.grid.major = element_blank(),
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom",
        plot.title = element_markdown(hjust = .5, size = 11),
        plot.title.position = "panel")

rennes_iv <- ggplot(st_intersection(st_buffer(uu35701_shp, 100), iv_shp),
       aes(color = reorder(feature, order_feature), fill = reorder(feature, order_feature))) +
  geom_sf(data = st_intersection(france, uu35701_shp), 
          fill = alpha(greys[1], alpha_fill), 
          color = alpha(greys[2], alpha_fill), 
          show.legend = F) + 
  geom_sf(data = st_union(st_intersection(france, uu35701_shp)), 
          fill = NA, 
          color = alpha(greys[2], 1), 
          show.legend = F) + 
  geom_sf(alpha = alpha_color) +
  scale_color_manual(values = c("steelblue", mypal[1:2])) + 
  scale_fill_manual(values = c("steelblue", mypal[1:2])) + 
  custom_theme() +
  ggtitle("Rennes") +
  theme(panel.grid.major = element_blank(),
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom",
        plot.title = element_markdown(hjust = .5, size = 11),
        plot.title.position = "panel")

limoges_iv <- ggplot(st_intersection(st_buffer(uu87601_shp, 100), iv_shp),
       aes(color = reorder(feature, order_feature), fill = reorder(feature, order_feature))) +
  geom_sf(data = st_intersection(france, uu87601_shp), 
          fill = alpha(greys[1], alpha_fill), 
          color = alpha(greys[2], alpha_fill), 
          show.legend = F) + 
  geom_sf(data = st_union(st_intersection(france, uu87601_shp)), 
          fill = NA, 
          color = alpha(greys[2], 1), 
          show.legend = F) + 
  geom_sf(alpha = alpha_color) +
  scale_color_manual(values = c("steelblue", mypal[1:2])) + 
  scale_fill_manual(values = c("steelblue", mypal[1:2])) + 
  custom_theme() +
  ggtitle("Limoges") +
  theme(panel.grid.major = element_blank(),
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom",
        plot.title = element_markdown(hjust = .5, size = 11),
        plot.title.position = "panel")


p <- wrap_plots(toulouse_iv + rennes_iv + limoges_iv) +
  plot_layout(guides = "collect") & 
  theme(legend.position = "bottom",
        plot.background = element_blank())

ggsave("../articles/sirugue_2024/out/ivs.png", p, width = bwidth, height = bheight, dpi = 400)
```
